AWSTemplateFormatVersion: 2010-09-09
Transform: "AWS::Serverless-2016-10-31"
Description: LambdaPipeline

Resources:
  OpenSearchServiceDomain:
    Type: AWS::OpenSearchService::Domain
    Properties:
      DomainName: photosearch
      EngineVersion: Elasticsearch_7.10
      ClusterConfig: 
        InstanceCount: 1
        InstanceType: t3.small.search
      EBSOptions:
        EBSEnabled: true
        VolumeSize: 10
        VolumeType: gp2
  search-photos-frontend:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: search-photos-frontend
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
  6998photoss:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: 6998photoss
  indexphotos:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: index-photos
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: ./index-photos
      Description: ''
      MemorySize: 128
      Timeout: 15
      Role: arn:aws:iam::862581198846:role/service-role/index-photos-role-wujmn61s
      Events:
        BucketEvent1:
          Type: S3
          Properties:
            Bucket:
              Ref: 6998photoss
            Events:
              - s3:ObjectCreated:Put
  searchphotos:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: search-photos
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: ./search-photos
      Description: ''
      MemorySize: 128
      Timeout: 15
      Role: arn:aws:iam::862581198846:role/service-role/search-photos-role-duuk95vl
      Events:
        PhotoApi:
          Type: Api
          Properties:
            Path: /search
            Method: GET
  PhotoApi:
    Type: AWS::ApiGateway::RestApi
    DependsOn: [6998photoss]
    Properties:
      # BodyS3Location:
      #   Bucket: codepipelines3
      #   Key: "swagger.yaml"
      Description: "Rest api having search photos and upload photos methods."
      Name: AI Photo Search
      BinaryMediaTypes: 
        - "*/*"
      FailOnWarnings: true
      EndpointConfiguration:
        Types:
          - "REGIONAL"
  PermissionForAPITosearchphotos:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt search-photos.Arn
      Principal: apigateway.amazonaws.com
      SourceAccount: !Ref "AWS::AccountId"
      SourceArn: !Join
        - ""
        - - "arn:aws:iam::862581198846:role/service-role/search-photos-role-duuk95vl"
          - !Ref PhotoApi
          - "/resources/*/methods/GET"
  PermissionForS3Toindexphotos:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref index-photos
      Principal: s3.amazonaws.com
      SourceAccount: !Ref "AWS::AccountId"
      SourceArn: "arn:aws:s3:::6998photoss"